OLED Configuratoin
SRA-VJTI/sra-board-component pull request #58
Opened 2022-03-03 19:37 UTC by gautam-dev-maker

This PR adds the following functionalities

* Solves the MPU6050 integration with OLED
* Add LSA bar funciont
* Add WallE logo function
* Add function to display MPU6050 readings on OLED

2022-03-05 13:33 UTC, VedantParanjape approved these changes

2022-03-05 13:34 UTC, VedantParanjape commented
@gautam-dev-maker can you change SRA logo to be white logo on black background. The current one is opposite of that and doesn't look that good on the OLED.

2022-03-05 13:37 UTC, VedantParanjape requested changes

2022-03-05 13:37 UTC, VedantParanjape commented on src/oled.c
> +esp_err_t display_lsa(line_sensor_array readings,u8g2_t *u8g2)
```suggestion
esp_err_t display_lsa(line_sensor_array readings, u8g2_t *u8g2)
```

2022-03-05 13:37 UTC, VedantParanjape commented on src/oled.c
> +    u8g2_DrawBitmap(u8g2,27,0,9,36,sra_logo);
```suggestion
    u8g2_DrawBitmap(u8g2, 27, 0, 9, 36, sra_logo);
```
Even though a nitpick, please run a linter to cleanup the code formatting in many places

2022-03-11 12:27 UTC, VedantParanjape commented
LGTM ! @gautam-dev-maker should I merge it ?

2022-03-11 12:28 UTC, gautam-dev-maker commented
Shouldl I make the README changes in this PR itself?

2022-03-11 12:28 UTC, VedantParanjape commented
> Shouldl I make the README changes in this PR itself?

Nope, can be done later. Necessary to get functional changes in.

2022-03-11 12:30 UTC, merged