MPU Calibration
SRA-VJTI/sra-board-component pull request #74
Opened 2022-12-09 09:57 UTC by RISHI27-dot

2023-01-08 13:21 UTC, VedantParanjape requested changes

2023-01-08 13:21 UTC, VedantParanjape commented on Kconfig
> +		sets the number of reading to take while taking average for MPU calibration
indentation is wrong, fix it

2023-01-08 13:21 UTC, VedantParanjape commented on include/mpu6050.h
> +esp_err_t calibrate(float *offset);
follow naming convention like other function, `calibrate_mpu6050`

2023-01-08 13:21 UTC, VedantParanjape commented on src/mpu6050.c
> +	complementary_filter(acce_raw_value_offset, gyro_raw_value_offset, offset, zero);
why is there a call to this in calibrate ?

2023-01-09 19:25 UTC, VedantParanjape commented on src/mpu6050.c
> +	complementary_filter(acce_raw_value_offset, gyro_raw_value_offset, offset, zero);
Okay, but why would you want to use complemented angle values ? offset is a raw value applied to gyro and accel readings separately.

Check this link: https://wired.chillibasket.com/2015/01/calibrating-mpu6050/

This needs some more implementation. CC: @gautam-dev-maker

2023-01-10 06:46 UTC, RISHI27-dot commented on src/mpu6050.c
> +	complementary_filter(acce_raw_value_offset, gyro_raw_value_offset, offset, zero);
I will complete the additional implementation by today.

2023-01-11 15:09 UTC, RISHI27-dot commented on src/mpu6050.c
> +	complementary_filter(acce_raw_value_offset, gyro_raw_value_offset, offset, zero);
> Check this link: https://wired.chillibasket.com/2015/01/calibrating-mpu6050/
I tried implementing this approach. In this approach offset is set in the the offset register of MPU, average of 1000 values is taken and the offset is adjusted and again set in the register of the MPU. This procedure is repeated untill the average value for gx, gy, gz are close to zero and ax, ay, az are close to 0, 0, 16348 respectively. This will give the optimum offset values for gyroscope and acceleromentr raw readings. But I faced following difficulties in implementing this approach

2023-01-11 15:37 UTC, RISHI27-dot commented on src/mpu6050.c
> +	complementary_filter(acce_raw_value_offset, gyro_raw_value_offset, offset, zero);
> Check this link: https://wired.chillibasket.com/2015/01/calibrating-mpu6050/

I tried implementing this approach, this approach writes the offset values in the offset registers on the MPU. After going through the data sheet for MPU6050 any dedicated register for offset MPU6050 was not found. I even tried backtracing the setter function used here form the [i2cdevlib](https://github.com/jrowberg/i2cdevlib) and writing to the same address in my code, but it gives abnormal behavior like the value written changes. My implementation of this approach can be found [here](https://github.com/SRA-VJTI/sra-board-component/compare/main...RISHI27-dot:sra-board-component:MPU_calibration_review).

2023-01-13 13:22 UTC, VedantParanjape requested changes

2023-01-13 13:22 UTC, VedantParanjape commented on src/mpu6050.c
> +esp_err_t avg_sensors(int16_t *acce_RV_avg, int16_t *gyro_RV_avg, int16_t *acce_offs, int16_t *gyro_offs)
This should be a static function, right ?

> acce_RV_avg, gyro_RV_avg

Follow the naming convention, acce_value_avg and gyro_value_avg. Just a example, name something similar.

2023-01-13 13:22 UTC, VedantParanjape commented on src/mpu6050.c
> +	while(1)
This can be stuck in an endless loop, implement using for-loop, if it exits without calibrating within error, show a warning message.

2023-01-13 13:22 UTC, VedantParanjape commented on src/mpu6050.c
> +	ESP_LOGI("acce offset vlaues", "%d | %d | %d", acce_raw_value_offset[0], acce_raw_value_offset[1], acce_raw_value_offset[2]);
1) spelling of values is wrong.
2) expand acce and gyro to full form in debug message.

2023-01-13 13:29 UTC, VedantParanjape commented
Still two things are not implemented.
1) void complementary_filter(int16_t *acce_raw_value, int16_t *gyro_raw_value, float *complementary_angle, float *mpu_offset) -> this doesn't internally use mpu_offset on gyro values

2) inside read_mpu6050(), call to complementary_filter function doesn't use the offset values defined above.

2023-01-13 13:30 UTC, VedantParanjape requested changes

2023-01-13 13:30 UTC, VedantParanjape commented on src/mpu6050.c
> +int16_t min_acce_error = 5;
all the three vars  (L31, L32, L33) should be static, right ?

2023-01-13 13:50 UTC, SAtacker requested changes

2023-01-13 13:50 UTC, SAtacker commented on src/mpu6050.c
> +int16_t acce_raw_value_offset[BUFF_SIZE / 2] = {0, 0, 0}, gyro_raw_value_offset[BUFF_SIZE / 2] = {0, 0, 0};
Define the reasoning and general experimentation approach here.

2023-01-13 13:50 UTC, SAtacker commented on src/mpu6050.c
> +int16_t acce_raw_value_offset[BUFF_SIZE / 2] = {0, 0, 0}, gyro_raw_value_offset[BUFF_SIZE / 2] = {0, 0, 0};
It should be either const or a simple macro can do the job; (min_*)

2023-01-13 13:50 UTC, SAtacker commented on src/mpu6050.c
> +esp_err_t avg_sensors(int16_t *acce_RV_avg, int16_t *gyro_RV_avg, int16_t *acce_offs, int16_t *gyro_offs)
constness should be added for var/vals that don't change

2023-01-13 13:50 UTC, SAtacker commented on src/mpu6050.c
> +		if (read_mpu6050_raw(curr_acce_raw_value, curr_gyro_raw_value) != ESP_OK)
In case this fails, the average calculated will be wrong. If we maintain a threshold to determine the minimum fail times it should be a bit better.

2023-01-13 13:50 UTC, SAtacker commented on src/mpu6050.c
> +	avg_sensors(acce_raw_value_avg, gyro_raw_value_avg, acce_raw_value_offset, gyro_raw_value_offset);
Similar to the above statement please check for the failure of this function. If it fails return the control flow back to the caller and let the caller know that calibration is failed.

2023-01-13 13:50 UTC, SAtacker commented on src/mpu6050.c
> +	acce_raw_value_offset[2] = (16384 - acce_raw_value_avg[2]);
please define the number `16384` as a const or a macro and state why that number

2023-01-13 13:50 UTC, SAtacker commented on src/mpu6050.c
> +	}
Calibrate a limited number of times to avoid infinite loop.

2023-01-14 12:54 UTC, SAtacker requested changes

2023-01-14 12:54 UTC, SAtacker commented on src/mpu6050.c
> +		if (i == MAX_CALIBRATION_ATTEMPTS)
how can `i` ever be equal to `MAX_CALIBRATION_ATTEMPTS`?

2023-01-14 12:54 UTC, SAtacker commented on src/mpu6050.c
> +		}
Add this after the execution of for loop

2023-01-14 13:16 UTC, RISHI27-dot commented on src/mpu6050.c
> +		if (i == MAX_CALIBRATION_ATTEMPTS)
I apologise for this error.

2023-01-14 13:32 UTC, SAtacker commented
Can you please mark the review as resolved if you have did it @RISHI27-dot ?

2023-01-14 16:06 UTC, VedantParanjape requested changes

2023-01-14 16:06 UTC, VedantParanjape commented on src/mpu6050.c
> +		else acce_raw_value_offset[2] += acce_raw_value_avg[2] - G_RAW_VLAUE;
> G_RAW_VLAUE

Grammarly chala bhai code pe 😄

2023-01-14 16:07 UTC, VedantParanjape commented
Other than that LGTM, @gautam-dev-maker can you do one final review?

2023-01-14 16:39 UTC, gautam-dev-maker commented
LGTM!

2023-01-14 16:41 UTC, gautam-dev-maker commented on src/mpu6050.c
> +	// static bool is_initial_reading = true;
Can this comments be removed?

2023-01-14 16:41 UTC, gautam-dev-maker commented on src/mpu6050.c
> +	// for(int i = 0; i < 3; i++)
Can these comments be removed as well?

2023-01-14 20:25 UTC, SAtacker approved these changes

2023-01-14 20:31 UTC, merged