MCPWM Implementation update for ESP-IDF 5.0
SRA-VJTI/sra-board-component pull request #90
Opened 2024-01-10 18:25 UTC by SuperChamp234

As per pull request #88  , I have rewritten the MCPWM implementation for ESP-IDF 5.0. It make use of the `driver/mcpwm_prelude.h` now.

This new MCPWM implementation requires the use of a `motor_handle_t` when trying to access the mcpwm object and perform actions.

Please review and let me know the changes, thank you.

2024-01-30 06:17 UTC, RISHI27-dot commented on CMakeLists.txt
> +                                esp_rom esp_timer freertos heap log soc spiffs)
LGTM

2024-01-30 06:17 UTC, RISHI27-dot commented on include/motor_driver.h
> +#pragma once
Use header guards instead of pragma.

2024-01-30 06:17 UTC, RISHI27-dot commented on src/mcpwm_interface.c
> +#include <sys/cdefs.h>
Remove these 3 included headers, as they are not required.

2024-01-30 06:17 UTC, RISHI27-dot commented on src/mcpwm_interface.c
> +#include "esp_log.h"
Including this is not required.

2024-01-30 06:17 UTC, RISHI27-dot commented on src/motor_driver.c
> +#include "esp_check.h"
Remove these 2 included headers, as they are not required.

2024-01-30 06:17 UTC, RISHI27-dot commented on src/motor_driver.c
> +#include "pin_defs.h"
Including this is not required.

2024-01-30 08:37 UTC, VedantParanjape commented on .gitignore
> -!.vscode/tasks.json
why are you removing all these?

2024-01-30 08:37 UTC, VedantParanjape commented on CMakeLists.txt
> +                                esp_rom esp_timer freertos heap log soc spiffs)
LGTM

2024-01-30 08:40 UTC, VedantParanjape commented on examples/motor_driver_normal/main/main.c
> -static const char* TAG_SWITCH_CONTROL_MOTOR = "switch_control";
Please use the tag char array to print logs, it's an unsaid rule in esp-idf.

2024-01-30 08:40 UTC, VedantParanjape commented on examples/motor_driver_normal/main/main.c
> +    motor_handle_t motor1;
indent nicely like before, add comments as well.

2024-01-30 08:41 UTC, VedantParanjape commented on include/motor_driver.h
> +#pragma once
+1

2024-01-30 09:03 UTC, VedantParanjape commented on src/i2cdev.c
LGTM!

2024-01-30 10:13 UTC, VedantParanjape requested changes
I will want to review once more, after Rishi finished the review.

2024-01-31 13:54 UTC, SuperChamp234 commented on src/motor_driver.c
> +#include "pin_defs.h"
This is required as we use the pindefs for creation of mcpwm config, and we use the map function from utils for mapping the PWM.

2024-01-31 13:54 UTC, SuperChamp234 commented on .gitignore
> -!.vscode/tasks.json
Do we need the `.vscode` files in the repository?

2024-01-31 14:05 UTC, SuperChamp234 commented on include/motor_driver.h
> +#pragma once
Changes made

2024-01-31 14:05 UTC, SuperChamp234 commented on src/mcpwm_interface.c
> +#include <sys/cdefs.h>
Changes made 👍🏽

2024-01-31 14:06 UTC, SuperChamp234 commented on src/mcpwm_interface.c
> +#include "esp_log.h"
Changes made 👍🏽

2024-01-31 14:06 UTC, SuperChamp234 commented on src/motor_driver.c
> +#include "esp_check.h"
Changed made 👍🏽

2024-01-31 14:06 UTC, SuperChamp234 commented on examples/motor_driver_normal/main/main.c
> -static const char* TAG_SWITCH_CONTROL_MOTOR = "switch_control";
Change made 👍🏽

2024-01-31 14:06 UTC, SuperChamp234 commented on examples/motor_driver_normal/main/main.c
> +    motor_handle_t motor1;
Change made 👍🏽

2024-01-31 14:08 UTC, RISHI27-dot commented on include/sra_board.h
LGTM!

2024-01-31 14:09 UTC, RISHI27-dot commented on CMakeLists.txt
LGTM

2024-01-31 14:10 UTC, RISHI27-dot commented on examples/motor_driver_normal/main/main.c
> +static const char* TAG = "MOTOR";
LGTM

2024-01-31 14:14 UTC, RISHI27-dot commented on include/motor_driver.h
> + * - ESP_FAIL: Failed
Indent this properly

2024-01-31 14:27 UTC, RISHI27-dot commented on src/motor_driver.c
> +	return ESP_OK;
LGTM.

2024-01-31 14:49 UTC, RISHI27-dot requested changes

2024-01-31 14:49 UTC, RISHI27-dot commented on src/motor_driver.c
LGTM!

2024-01-31 14:49 UTC, RISHI27-dot commented on include/mcpwm_interface.h
LGTM.

2024-01-31 14:49 UTC, RISHI27-dot commented on src/mcpwm_interface.c
LGTM!

2024-01-31 14:49 UTC, RISHI27-dot commented on include/motor_driver.h
> +int get_motor_driver_status();
This looks good.

2024-01-31 14:49 UTC, RISHI27-dot commented on include/motor_driver.h
> +#endif
Check for redundant addition of new lines.

2024-01-31 14:49 UTC, RISHI27-dot commented on src/bar_graph.c
LGTM!

2024-01-31 14:49 UTC, RISHI27-dot commented on src/motor_driver.c
> +#include "pin_defs.h"
ok

2024-01-31 14:49 UTC, RISHI27-dot commented on include/utils.h
> +#include "esp_log.h"
Remove this include if not required.

2024-01-31 15:06 UTC, RISHI27-dot approved these changes
@VedantParanjape The Wall-E bot successfully achieves self-balancing through the implemented MCPWM driver, and I have completed my review. Please add your reviews  so that we can proceed with merging.

2024-02-01 03:18 UTC, RISHI27-dot commented on src/motor_driver.c
> +	speed = (uint32_t)map(speed, 0, 100, 0, MCPWM_RESOLUTION / MCPWM_FREQ);
@SuperChamp234  Please add a description of how this mapping is done in the commit message.

2024-02-01 09:10 UTC, merged